name: Setup Android

inputs:
  google-services-json-base64-dev:
    description: secrets.GOOGLE_SERVICES_JSON_BASE64_DEV
    required: true
  google-services-json-base64-prod:
    description: secrets.GOOGLE_SERVICES_JSON_BASE64_PROD
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup JDK
      uses: actions/setup-java@v5
      with:
        distribution: 'zulu'
        java-version: '17'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v6
    - name: Create google-services.json
      run: |
        mkdir -p android/app/src/dev
        printf '%s' "$GOOGLE_SERVICES_JSON_BASE64_DEV" | base64 --decode > android/app/src/dev/google-services.json
        mkdir -p android/app/src/prod
        printf '%s' "$GOOGLE_SERVICES_JSON_BASE64_PROD" | base64 --decode > android/app/src/prod/google-services.json
      env:
        GOOGLE_SERVICES_JSON_BASE64_DEV: ${{ inputs.google-services-json-base64-dev }}
        GOOGLE_SERVICES_JSON_BASE64_PROD: ${{ inputs.google-services-json-base64-prod }}
      shell: bash
