name: CI

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  android-lint:
    name: Android Lint
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Android
        uses: ../.github/actions/setup-android
      - name: Run Android Lint
        run: ./gradlew lintDebug
        env:
          GOOGLE_MAPS_API_KEY_DEV: ${{ secrets.GOOGLE_MAPS_API_KEY_DEV }}
          GOOGLE_MAPS_API_KEY_PROD: ${{ secrets.GOOGLE_MAPS_API_KEY_PROD }}

  ktlint:
    name: ktlint
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Android
        uses: ../.github/actions/setup-android
      - name: Run ktlint
        run: ./gradlew ktlintCheck
        env:
          GOOGLE_MAPS_API_KEY_DEV: ${{ secrets.GOOGLE_MAPS_API_KEY_DEV }}
          GOOGLE_MAPS_API_KEY_PROD: ${{ secrets.GOOGLE_MAPS_API_KEY_PROD }}

  unit-test-kmp-android:
    name: Unit Test
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Android
        uses: ../.github/actions/setup-android
      - name: Run Unit Test
        run: ./gradlew testDebug
        env:
          GOOGLE_MAPS_API_KEY_DEV: ${{ secrets.GOOGLE_MAPS_API_KEY_DEV }}
          GOOGLE_MAPS_API_KEY_PROD: ${{ secrets.GOOGLE_MAPS_API_KEY_PROD }}
